version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "groupsky"

  - package-ecosystem: "docker"
    directory: "/docker/portainer"
    schedule:
      interval: "daily"
    reviewers:
      - "groupsky"

  - package-ecosystem: "docker"
    directory: "/docker/portainer-agent"
    schedule:
      interval: "daily"
    reviewers:
      - "groupsky"
